server:
  port: 5111

jwt:
  secret: ZXZnZWVr5b+r5LmQ5L2g55qE5Ye66KGM
  filter:
    should_not_filter:
      - /openapi/login




##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

zuul:
  #最大连接数
  max:
    host:
      connections: 500

  #超时配置
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

  #路径配置
  routes:
    #用户模块
    managerapi:
      stripPrefix: true
      path: /managerapi/**
      sensitiveHeaders:

ribbon:
  eureka:
    enabled: false

  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 3

msadminapi:
  ribbon:
    listOfServers: 192.168.1.184:6111

spring:
  data:
  datasource:

  redis:
    database: 0
    host: 192.168.1.101
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0

